const uiTokenPolicyConfig = {
  files: [
    'src/styles/generated/brand.css',
    'src/styles/munjanggun-brand.css',
    'src/styles/blog-experience.css',
    'src/components/blog/BlogPostRenderer.module.css',
    'src/components/platform/ui/PlatformButton.module.css',
    'src/components/platform/ui/PlatformCheckbox.module.css',
    'src/components/platform/ui/PlatformChip.module.css',
    'src/components/platform/ui/PlatformIconButton.module.css',
    'src/components/platform/ui/PlatformList.module.css',
    'src/components/platform/ui/PlatformSegmentedControl.module.css',
    'src/components/platform/ui/PlatformStatusBadge.module.css',
    'src/components/platform/ui/PlatformSwitch.module.css',
    'src/components/platform/ui/PlatformPageHeader.module.css',
    'src/components/platform/ui/PlatformPanel.module.css',
    'src/components/platform/ui/PlatformPreviewFrame.module.css',
    'src/components/platform/ui/PlatformStatePanel.module.css',
    'src/components/platform/ui/PlatformField.module.css',
    'src/components/platform/ui/PlatformEditorSection.module.css',
    'src/components/platform/ui/PlatformModal.module.css',
    'src/components/platform/ui/PlatformSelect.module.css',
    'src/components/platform/ui/PlatformToolbar.module.css',
    'src/components/platform/ui/PlatformTabs.module.css',
    'src/components/platform/ui/PlatformTable.module.css',
    'src/components/admin/NodeAddModal.module.css',
    'src/components/admin/NodeMoveModal.module.css',
    'src/components/admin/NodeList.module.css',
    'src/components/admin/SiteSettingsForm.module.css',
    'src/app/admin/settings/settings.module.css',
    'src/app/admin/error.module.css',
    'src/app/admin/platform/[id]/platform-detail.module.css',
    'src/app/admin/layout.module.css',
    'src/app/admin/login/login.module.css',
    'src/app/admin/nodes/[id]/page.module.css',
    'src/app/admin/platform/assets/assets.module.css',
    'src/app/admin/platform/blog/[id]/blog-editor.module.css',
    'src/app/admin/platform/blog/[id]/preview/preview.module.css',
    'src/app/admin/platform/blog/blog-draft-queue.module.css',
    'src/app/admin/platform/blog/new/approved-manuscript-intake.module.css',
    'src/app/admin/platform/platform-admin.module.css',
    'src/app/admin/platform/settings/settings.module.css',
    'src/components/admin/AdminRouteLoading.module.css',
    'src/components/admin/AdminSidebar.module.css',
    'src/components/admin/CollectionForm.module.css',
    'src/components/admin/ColorForm.module.css',
    'src/components/admin/GalleryManager.module.css',
    'src/components/admin/HeroConfigurator.module.css',
    'src/components/admin/ImageUploader.module.css',
    'src/components/admin/NodeForm.module.css',
    'src/components/admin/StatusBadge.module.css',
  ],
  requiredCssDirectories: ['src/app/admin', 'src/components/admin'],
  strictLayoutFiles: ['src/components/blog/BlogPostRenderer.module.css'],
  generatedFiles: ['src/styles/generated/brand.css'],
  tokenDefinitionFiles: ['src/app/globals.css'],
  tokenDefinitionScopes: [
    { file: 'src/app/globals.css', selectors: [':root'] },
  ],
  globalDefinitionFiles: [
    'src/styles/munjanggun-brand.css',
    'src/styles/blog-experience.css',
  ],
  generatedTokenOverrideScopes: [
    {
      file: 'src/styles/munjanggun-brand.css',
      selectors: [
        '[data-mg-theme="portal"]',
        '[data-mg-theme="showroom-dark"]',
        '[data-mg-theme="admin"]',
      ],
    },
  ],
  declarationAllowlist: [
    '--mg-action-primary',
    '--mg-action-primary-active',
    '--mg-action-primary-bg',
    '--mg-action-primary-fg',
    '--mg-action-primary-hover',
    '--mg-action-primary-text',
    '--mg-action-secondary',
    '--mg-action-secondary-hover',
    '--mg-action-secondary-text',
    '--mg-admin-accent-border',
    '--mg-admin-accent-surface',
    '--mg-admin-accent-text',
    '--mg-admin-preview-chrome-height',
    '--mg-admin-preview-device-width',
    '--mg-admin-preview-handle-height',
    '--mg-admin-preview-handle-width',
    '--mg-admin-preview-ratio-height',
    '--mg-admin-preview-ratio-width',
    '--mg-admin-preview-scroll-max-height',
    '--mg-admin-preview-scroll-offset',
    '--mg-almond-soft',
    '--mg-bg',
    '--mg-blog-accent',
    '--mg-blog-accent-strong',
    '--mg-blog-body',
    '--mg-blog-border',
    '--mg-blog-border-strong',
    '--mg-blog-canvas',
    '--mg-blog-canvas-subtle',
    '--mg-blog-control-size',
    '--mg-blog-cta-surface',
    '--mg-blog-ease-expressive',
    '--mg-blog-font-body',
    '--mg-blog-font-display',
    '--mg-blog-font-wordmark',
    '--mg-blog-glass-border-dark',
    '--mg-blog-glass-border-light',
    '--mg-blog-glass-dark',
    '--mg-blog-glass-hero',
    '--mg-blog-glass-light',
    '--mg-blog-glass-panel',
    '--mg-blog-ink',
    '--mg-blog-inverse',
    '--mg-blog-layout-gutter',
    '--mg-blog-layout-section',
    '--mg-blog-motion-fast',
    '--mg-blog-motion-navigation',
    '--mg-blog-motion-standard',
    '--mg-blog-muted',
    '--mg-blog-radius-card',
    '--mg-blog-radius-compact',
    '--mg-blog-radius-cta',
    '--mg-blog-radius-floating',
    '--mg-blog-radius-footer',
    '--mg-blog-radius-media',
    '--mg-blog-radius-search',
    '--mg-blog-reader-caution-surface',
    '--mg-blog-reader-chip-border',
    '--mg-blog-reader-chip-line',
    '--mg-blog-reader-empty-surface',
    '--mg-blog-reader-glass-72',
    '--mg-blog-reader-glass-78',
    '--mg-blog-reader-glass-90',
    '--mg-blog-reader-highlight',
    '--mg-blog-reader-mobile-action-offset',
    '--mg-blog-reader-back-link-height',
    '--mg-blog-reader-border-width',
    '--mg-blog-reader-card-lift',
    '--mg-blog-reader-chip-height',
    '--mg-blog-reader-content-max',
    '--mg-blog-reader-font-body',
    '--mg-blog-reader-font-body-comfortable',
    '--mg-blog-reader-font-body-lg',
    '--mg-blog-reader-font-caption',
    '--mg-blog-reader-font-card',
    '--mg-blog-reader-font-card-comfortable',
    '--mg-blog-reader-font-heading',
    '--mg-blog-reader-font-heading-compact',
    '--mg-blog-reader-font-heading-mobile',
    '--mg-blog-reader-font-hero',
    '--mg-blog-reader-font-hero-mobile',
    '--mg-blog-reader-font-label',
    '--mg-blog-reader-font-question',
    '--mg-blog-reader-hero-media-min',
    '--mg-blog-reader-jump-height',
    '--mg-blog-reader-next-height',
    '--mg-blog-reader-notice',
    '--mg-blog-reader-notice-text',
    '--mg-blog-reader-scroll-offset',
    '--mg-blog-reader-shadow-hover',
    '--mg-blog-reader-shadow-ink',
    '--mg-blog-reader-shadow-soft',
    '--mg-blog-reader-proof-height',
    '--mg-blog-reader-question-icon-offset',
    '--mg-blog-reader-question-icon-track',
    '--mg-blog-reader-shell-max',
    '--mg-blog-reader-title-max',
    '--mg-blog-reader-warning-border',
    '--mg-blog-reader-warning-surface',
    '--mg-blog-reader-warning-text',
    '--mg-blog-reader-warm-glass-base',
    '--mg-blog-shadow-card',
    '--mg-blog-shadow-floating',
    '--mg-blog-shadow-overlay',
    '--mg-blog-status-danger',
    '--mg-blog-status-success',
    '--mg-blog-surface',
    '--mg-blog-surface-muted',
    '--mg-body-warm',
    '--mg-border-strong',
    '--mg-border-subtle',
    '--mg-button-height-sm',
    '--mg-cashmere-cream',
    '--mg-caution-red',
    '--mg-clay-terracotta',
    '--mg-clay-terracotta-hover',
    '--mg-cocoa-oak',
    '--mg-cream-soft',
    '--mg-current-bg',
    '--mg-current-body',
    '--mg-current-caption',
    '--mg-current-display-hero',
    '--mg-current-display-section',
    '--mg-current-label',
    '--mg-current-surface',
    '--mg-current-text',
    '--mg-current-title',
    '--mg-disabled-surface',
    '--mg-disabled-text',
    '--mg-fg',
    '--mg-focus-ring',
    '--mg-focus-shadow',
    '--mg-focus-shadow-soft',
    '--mg-focus-shadow-inset',
    '--mg-font-brand-ko',
    '--mg-font-latin',
    '--mg-font-size-body-mobile',
    '--mg-font-size-caption-mobile',
    '--mg-font-size-display-hero',
    '--mg-font-size-display-hero-mobile',
    '--mg-font-size-display-section',
    '--mg-font-size-display-section-mobile',
    '--mg-font-size-label-mobile',
    '--mg-font-weight-display',
    '--mg-font-weight-label',
    '--mg-font-weight-regular',
    '--mg-font-weight-strong',
    '--mg-form-field-height',
    '--mg-ink-warm',
    '--mg-kakao-bg',
    '--mg-kakao-text',
    '--mg-letter-spacing',
    '--mg-line-height-body-strong',
    '--mg-line-height-caption',
    '--mg-line-height-display-hero',
    '--mg-line-height-display-section',
    '--mg-line-height-label',
    '--mg-line-height-title',
    '--mg-muted-warm',
    '--mg-navy-soft',
    '--mg-on-dark',
    '--mg-on-terracotta',
    '--mg-overlay-scrim',
    '--mg-overlay-scrim-strong',
    '--mg-paper-white',
    '--mg-radius-md',
    '--mg-radius-sm',
    '--mg-radius-xs',
    '--mg-shadow-elevated',
    '--mg-shadow-hairline',
    '--mg-space-lg',
    '--mg-space-md',
    '--mg-space-section',
    '--mg-space-sm',
    '--mg-space-xl',
    '--mg-space-xs',
    '--mg-space-xxl',
    '--mg-state-danger',
    '--mg-state-danger-hover',
    '--mg-state-danger-border',
    '--mg-state-danger-surface',
    '--mg-state-pending',
    '--mg-state-pending-border',
    '--mg-state-pending-surface',
    '--mg-state-proof',
    '--mg-state-proof-border',
    '--mg-state-proof-surface',
    '--mg-state-success',
    '--mg-state-success-border',
    '--mg-state-success-surface',
    '--mg-success-green',
    '--mg-surface',
    '--mg-surface-card',
    '--mg-surface-card-subtle',
    '--mg-surface-inverse',
    '--mg-surface-page',
    '--mg-surface-page-soft',
    '--mg-surface-raised',
    '--mg-surface-sunken',
    '--mg-surface-translucent',
    '--mg-text-body',
    '--mg-text-muted',
    '--mg-text-primary',
    '--mg-text-soft',
    '--mg-toasted-almond',
    '--mg-verified-navy',
    '--mg-warm-line',
    '--mg-warm-line-strong',
  ],
  rawValueTokenAllowlist: [
    '--mg-admin-preview-chrome-height',
    '--mg-admin-preview-device-width',
    '--mg-admin-preview-handle-height',
    '--mg-admin-preview-handle-width',
    '--mg-admin-preview-ratio-height',
    '--mg-admin-preview-ratio-width',
    '--mg-admin-preview-scroll-max-height',
    '--mg-admin-preview-scroll-offset',
    '--mg-kakao-bg',
    '--mg-kakao-text',
    // Approved reader parity primitives are declared once in blog-experience.css.
    '--mg-blog-reader-caution-surface',
    '--mg-blog-reader-chip-line',
    '--mg-blog-reader-empty-surface',
    '--mg-blog-reader-highlight',
    '--mg-blog-reader-notice',
    '--mg-blog-reader-notice-text',
    '--mg-blog-reader-shadow-ink',
    '--mg-blog-reader-warning-border',
    '--mg-blog-reader-warning-surface',
    '--mg-blog-reader-warning-text',
    '--mg-blog-reader-warm-glass-base',
  ],
  externalDefinitions: [
    '--admin-bg',
    '--admin-route-block-inset',
    '--admin-border',
    '--admin-surface',
    '--admin-surface-elevated',
    '--admin-text',
    '--admin-text-muted',
    '--admin-text-sub',
    '--color-accent',
    '--color-accent-foreground',
    '--color-accent-hover',
    '--color-bg',
    '--color-border',
    '--color-ring',
    '--color-surface',
    '--color-surface-elevated',
    '--color-text',
    '--color-text-muted',
    '--color-text-sub',
    '--font-regular',
  ],
  sharedLayoutConstants: [
    { name: 'admin-narrow-phone-breakpoint', property: '@media', value: '380px' },
    { name: 'admin-preview-phone-breakpoint', property: '@media', value: '430px' },
    { name: 'admin-compact-form-breakpoint', property: '@media', value: '479px' },
    { name: 'admin-dialog-breakpoint', property: '@media', value: '520px' },
    { name: 'admin-settings-grid-breakpoint', property: '@media', value: '600px' },
    { name: 'admin-mobile-breakpoint', property: '@media', value: '639px' },
    { name: 'admin-mobile-alias-breakpoint', property: '@media', value: '640px' },
    { name: 'admin-compact-table-breakpoint', property: '@media', value: '720px' },
    { name: 'admin-settings-compact-breakpoint', property: '@media', value: '760px' },
    { name: 'admin-tablet-breakpoint', property: '@media', value: '768px' },
    { name: 'admin-tablet-table-max-breakpoint', property: '@media', value: '899px' },
    { name: 'admin-tablet-table-breakpoint', property: '@media', value: '900px' },
    { name: 'admin-workspace-max-breakpoint', property: '@media', value: '979px' },
    { name: 'admin-workspace-breakpoint', property: '@media', value: '980px' },
    { name: 'admin-desktop-breakpoint', property: '@media', value: '1024px' },
    { name: 'admin-wide-max-breakpoint', property: '@media', value: '1179px' },
    { name: 'admin-wide-breakpoint', property: '@media', value: '1180px' },
    { name: 'admin-preview-wide-max-breakpoint', property: '@media', value: '1279px' },
  ],
  layoutConstants: [
    {
      name: 'admin-preview-device-width',
      file: 'src/styles/munjanggun-brand.css',
      property: '--mg-admin-preview-device-width',
      value: '390px',
    },
    {
      name: 'admin-preview-chrome-height',
      file: 'src/styles/munjanggun-brand.css',
      property: '--mg-admin-preview-chrome-height',
      value: '34px',
    },
    {
      name: 'admin-preview-handle-width',
      file: 'src/styles/munjanggun-brand.css',
      property: '--mg-admin-preview-handle-width',
      value: '72px',
    },
    {
      name: 'admin-preview-handle-height',
      file: 'src/styles/munjanggun-brand.css',
      property: '--mg-admin-preview-handle-height',
      value: '5px',
    },
    {
      name: 'admin-preview-scroll-max-height',
      file: 'src/styles/munjanggun-brand.css',
      property: '--mg-admin-preview-scroll-max-height',
      value: '840px',
    },
    {
      name: 'admin-preview-scroll-offset',
      file: 'src/styles/munjanggun-brand.css',
      property: '--mg-admin-preview-scroll-offset',
      value: '244px',
    },
    {
      name: 'legacy-small-control-height',
      file: 'src/styles/munjanggun-brand.css',
      property: '--mg-button-height-sm',
      value: '40px',
    },
    {
      name: 'legacy-mobile-alias-breakpoint',
      file: 'src/styles/munjanggun-brand.css',
      property: '@media',
      value: '640px',
    },
    {
      name: 'approved-blog-search-radius',
      file: 'src/styles/blog-experience.css',
      property: '--mg-blog-radius-search',
      value: '28px',
    },
    {
      name: 'approved-blog-cta-radius',
      file: 'src/styles/blog-experience.css',
      property: '--mg-blog-radius-cta',
      value: '30px',
    },
    {
      name: 'approved-blog-tablet-breakpoint',
      file: 'src/styles/blog-experience.css',
      property: '@media',
      value: '960px',
    },
    {
      name: 'approved-blog-mobile-breakpoint',
      file: 'src/styles/blog-experience.css',
      property: '@media',
      value: '620px',
    },
    {
      name: 'approved-blog-tablet-section-spacing',
      file: 'src/styles/blog-experience.css',
      property: '--mg-blog-layout-section',
      value: '104px',
    },
    {
      name: 'approved-blog-mobile-section-spacing',
      file: 'src/styles/blog-experience.css',
      property: '--mg-blog-layout-section',
      value: '84px',
    },
    {
      name: 'admin-page-header-mobile-breakpoint',
      file: 'src/components/platform/ui/PlatformPageHeader.module.css',
      property: '@media',
      value: '639px',
    },
    {
      name: 'admin-editor-section-mobile-breakpoint',
      file: 'src/components/platform/ui/PlatformEditorSection.module.css',
      property: '@media',
      value: '639px',
    },
    {
      name: 'admin-state-panel-mobile-breakpoint',
      file: 'src/components/platform/ui/PlatformStatePanel.module.css',
      property: '@media',
      value: '639px',
    },
    {
      name: 'admin-node-list-mobile-breakpoint',
      file: 'src/components/admin/NodeList.module.css',
      property: '@media',
      value: '639px',
    },
    {
      name: 'admin-site-settings-mobile-breakpoint',
      file: 'src/components/admin/SiteSettingsForm.module.css',
      property: '@media',
      value: '639px',
    },
    {
      name: 'admin-detail-compact-form-breakpoint',
      file: 'src/app/admin/platform/[id]/platform-detail.module.css',
      property: '@media',
      value: '480px',
    },
    {
      name: 'admin-detail-wide-layout-breakpoint',
      file: 'src/app/admin/platform/[id]/platform-detail.module.css',
      property: '@media',
      value: '768px',
    },
    {
      name: 'admin-detail-mobile-layout-breakpoint',
      file: 'src/app/admin/platform/[id]/platform-detail.module.css',
      property: '@media',
      value: '479px',
    },
    {
      name: 'blog-reader-collapse-breakpoint',
      file: 'src/components/blog/BlogPostRenderer.module.css',
      property: '@media',
      value: '820px',
    },
    {
      name: 'blog-reader-mobile-actions-breakpoint',
      file: 'src/components/blog/BlogPostRenderer.module.css',
      property: '@media',
      value: '767px',
    },
    {
      name: 'blog-reader-preview-collapse-container',
      file: 'src/components/blog/BlogPostRenderer.module.css',
      property: '@container',
      value: '820px',
    },
    {
      name: 'blog-reader-preview-phone-container',
      file: 'src/components/blog/BlogPostRenderer.module.css',
      property: '@container',
      value: '430px',
    },
  ],
}

export default uiTokenPolicyConfig
