const uiTokenPolicyConfig = {
  files: [
    'src/styles/generated/brand.css',
    'src/styles/munjanggun-brand.css',
    'src/styles/blog-experience.css',
    'src/app/blog/blog.module.css',
    'src/app/blog/BlogBrandWordmark.module.css',
    'src/app/blog/BlogConditionComposer.module.css',
    'src/app/blog/BlogFinalExperience.module.css',
    'src/app/blog/BlogHomeHero.module.css',
    'src/app/blog/BlogStoryStage.module.css',
    'src/app/blog/BlogTopicRail.module.css',
    'src/components/blog/BlogArticleActions.module.css',
    'src/components/blog/BlogConditionChecklist.module.css',
    'src/components/blog/BlogNavigation.module.css',
    'src/components/blog/BlogPostRenderer.module.css',
    'src/components/customer/PublicUserMenu.module.css',
    'src/components/platform/ui/PlatformBadge.module.css',
    'src/components/platform/ui/PlatformButton.module.css',
    'src/components/platform/ui/PlatformCard.module.css',
    'src/components/platform/ui/PlatformCheckbox.module.css',
    'src/components/platform/ui/PlatformChip.module.css',
    'src/components/platform/ui/PlatformIconButton.module.css',
    'src/components/platform/ui/PlatformList.module.css',
    'src/components/platform/ui/PlatformSegmentedControl.module.css',
    'src/components/platform/ui/PlatformShell.module.css',
    'src/components/platform/ui/PlatformStatusBadge.module.css',
    'src/components/platform/ui/PlatformSwitch.module.css',
    'src/components/platform/ui/PlatformPageHeader.module.css',
    'src/components/platform/ui/PlatformPanel.module.css',
    'src/components/platform/ui/PlatformPreviewFrame.module.css',
    'src/components/platform/ui/PlatformStatePanel.module.css',
    'src/components/platform/ui/PlatformField.module.css',
    'src/components/platform/ui/PlatformEditorSection.module.css',
    'src/components/platform/ui/PlatformModal.module.css',
    'src/components/platform/ui/PlatformSelect.module.css',
    'src/components/platform/ui/PlatformToolbar.module.css',
    'src/components/platform/ui/PlatformTabs.module.css',
    'src/components/platform/ui/PlatformTable.module.css',
    'src/components/admin/NodeAddModal.module.css',
    'src/components/admin/NodeMoveModal.module.css',
    'src/components/admin/NodeList.module.css',
    'src/components/admin/SiteSettingsForm.module.css',
    'src/app/admin/settings/settings.module.css',
    'src/app/admin/error.module.css',
    'src/app/admin/platform/[id]/platform-detail.module.css',
    'src/app/admin/layout.module.css',
    'src/app/admin/login/login.module.css',
    'src/app/admin/nodes/[id]/page.module.css',
    'src/app/admin/platform/assets/assets.module.css',
    'src/app/admin/platform/blog/[id]/blog-editor.module.css',
    'src/app/admin/platform/blog/[id]/preview/preview.module.css',
    'src/app/admin/platform/blog/blog-draft-queue.module.css',
    'src/app/admin/platform/blog/new/approved-manuscript-intake.module.css',
    'src/app/admin/platform/platform-admin.module.css',
    'src/app/admin/platform/settings/settings.module.css',
    'src/app/preview/[token]/preview.module.css',
    'src/components/admin/AdminRouteLoading.module.css',
    'src/components/admin/AdminSidebar.module.css',
    'src/components/admin/CollectionForm.module.css',
    'src/components/admin/ColorForm.module.css',
    'src/components/admin/GalleryManager.module.css',
    'src/components/admin/HeroConfigurator.module.css',
    'src/components/admin/ImageUploader.module.css',
    'src/components/admin/NodeForm.module.css',
    'src/components/admin/StatusBadge.module.css',
  ],
  requiredCssDirectories: [
    'src/app/admin',
    'src/components/admin',
    'src/app/blog',
    'src/components/blog',
    'src/components/platform/ui',
  ],
  requiredCssFiles: [
    'src/app/preview/[token]/preview.module.css',
    'src/components/customer/PublicUserMenu.module.css',
  ],
  strictLayoutDirectories: [
    'src/app/admin',
    'src/components/admin',
    'src/app/blog',
    'src/components/blog',
    'src/components/platform/ui',
  ],
  strictLayoutFilesRequired: [
    'src/app/preview/[token]/preview.module.css',
    'src/components/customer/PublicUserMenu.module.css',
  ],
  strictLayoutFiles: ['src/components/blog/BlogPostRenderer.module.css'],
  generatedFiles: ['src/styles/generated/brand.css'],
  tokenDefinitionFiles: ['src/app/globals.css'],
  tokenDefinitionScopes: [
    { file: 'src/app/globals.css', selectors: [':root'] },
    {
      file: 'src/styles/blog-experience.css',
      selectors: [
        '[data-mg-theme="blog"]',
        '[data-mg-theme="blog"][data-mg-blog-experience="showroom"]',
      ],
    },
  ],
  globalDefinitionFiles: [
    'src/styles/munjanggun-brand.css',
    'src/styles/blog-experience.css',
  ],
  generatedTokenOverrideScopes: [
    {
      file: 'src/styles/munjanggun-brand.css',
      selectors: [
        '[data-mg-theme="portal"]',
        '[data-mg-theme="showroom-dark"]',
        '[data-mg-theme="admin"]',
      ],
    },
  ],
  declarationAllowlist: [
    '--mg-action-primary',
    '--mg-action-primary-active',
    '--mg-action-primary-bg',
    '--mg-action-primary-fg',
    '--mg-action-primary-hover',
    '--mg-action-primary-text',
    '--mg-action-secondary',
    '--mg-action-secondary-hover',
    '--mg-action-secondary-text',
    '--mg-admin-accent-border',
    '--mg-admin-accent-surface',
    '--mg-admin-accent-text',
    '--mg-admin-preview-chrome-height',
    '--mg-admin-preview-device-width',
    '--mg-admin-preview-handle-height',
    '--mg-admin-preview-handle-width',
    '--mg-admin-preview-ratio-height',
    '--mg-admin-preview-ratio-width',
    '--mg-admin-preview-scroll-max-height',
    '--mg-admin-preview-scroll-offset',
    '--mg-almond-soft',
    '--mg-bg',
    '--mg-blog-accent',
    '--mg-blog-accent-strong',
    '--mg-blog-body',
    '--mg-blog-border',
    '--mg-blog-border-strong',
    '--mg-blog-blur-glass',
    '--mg-blog-blur-soft',
    '--mg-blog-canvas',
    '--mg-blog-canvas-subtle',
    '--mg-blog-control-size',
    '--mg-blog-control-comfortable',
    '--mg-blog-control-hero',
    '--mg-blog-control-large',
    '--mg-blog-control-min',
    '--mg-blog-cta-surface',
    '--mg-blog-ease-expressive',
    '--mg-blog-font-body',
    '--mg-blog-font-display',
    '--mg-blog-font-wordmark',
    '--mg-blog-frame-bleed',
    '--mg-blog-frame-canvas',
    '--mg-blog-frame-card',
    '--mg-blog-frame-card-narrow',
    '--mg-blog-frame-compact',
    '--mg-blog-frame-content',
    '--mg-blog-frame-marker',
    '--mg-blog-frame-media',
    '--mg-blog-frame-panel',
    '--mg-blog-frame-rail',
    '--mg-blog-frame-reading',
    '--mg-blog-frame-shell',
    '--mg-blog-frame-stage',
    '--mg-blog-frame-thumbnail',
    '--mg-blog-frame-wide',
    '--mg-blog-glass-border-dark',
    '--mg-blog-glass-border-light',
    '--mg-blog-glass-dark',
    '--mg-blog-glass-hero',
    '--mg-blog-glass-light',
    '--mg-blog-glass-panel',
    '--mg-blog-ink',
    '--mg-blog-inverse',
    '--mg-blog-icon-compact',
    '--mg-blog-layout-gutter',
    '--mg-blog-layout-section',
    '--mg-blog-motion-fast',
    '--mg-blog-motion-navigation',
    '--mg-blog-motion-standard',
    '--mg-blog-muted',
    '--mg-blog-offset-hairline',
    '--mg-blog-radius-card',
    '--mg-blog-radius-compact',
    '--mg-blog-radius-cta',
    '--mg-blog-radius-floating',
    '--mg-blog-radius-footer',
    '--mg-blog-radius-media',
    '--mg-blog-radius-search',
    '--mg-blog-reader-caution-surface',
    '--mg-blog-reader-chip-border',
    '--mg-blog-reader-chip-line',
    '--mg-blog-reader-empty-surface',
    '--mg-blog-reader-glass-72',
    '--mg-blog-reader-glass-78',
    '--mg-blog-reader-glass-90',
    '--mg-blog-reader-highlight',
    '--mg-blog-reader-mobile-action-offset',
    '--mg-blog-reader-back-link-height',
    '--mg-blog-reader-border-width',
    '--mg-blog-reader-card-lift',
    '--mg-blog-reader-chip-height',
    '--mg-blog-reader-content-max',
    '--mg-blog-reader-font-body',
    '--mg-blog-reader-font-body-comfortable',
    '--mg-blog-reader-font-body-lg',
    '--mg-blog-reader-font-caption',
    '--mg-blog-reader-font-card',
    '--mg-blog-reader-font-card-comfortable',
    '--mg-blog-reader-font-heading',
    '--mg-blog-reader-font-heading-compact',
    '--mg-blog-reader-font-heading-mobile',
    '--mg-blog-reader-font-hero',
    '--mg-blog-reader-font-hero-mobile',
    '--mg-blog-reader-font-label',
    '--mg-blog-reader-font-question',
    '--mg-blog-reader-hero-media-min',
    '--mg-blog-reader-jump-height',
    '--mg-blog-reader-next-height',
    '--mg-blog-reader-notice',
    '--mg-blog-reader-notice-text',
    '--mg-blog-reader-scroll-offset',
    '--mg-blog-reader-shadow-hover',
    '--mg-blog-reader-shadow-ink',
    '--mg-blog-reader-shadow-soft',
    '--mg-blog-reader-proof-height',
    '--mg-blog-reader-question-icon-offset',
    '--mg-blog-reader-question-icon-track',
    '--mg-blog-reader-shell-max',
    '--mg-blog-reader-title-max',
    '--mg-blog-reader-warning-border',
    '--mg-blog-reader-warning-surface',
    '--mg-blog-reader-warning-text',
    '--mg-blog-reader-warm-glass-base',
    '--mg-blog-shadow-card',
    '--mg-blog-shadow-floating',
    '--mg-blog-shadow-overlay',
    '--mg-blog-showroom-shadow-compact',
    '--mg-blog-showroom-shadow-elevated',
    '--mg-blog-showroom-shadow-footer',
    '--mg-blog-showroom-shadow-glass',
    '--mg-blog-showroom-shadow-hero',
    '--mg-blog-showroom-shadow-inset',
    '--mg-blog-showroom-shadow-modal',
    '--mg-blog-showroom-shadow-outlined',
    '--mg-blog-showroom-shadow-strong',
    '--mg-blog-status-danger',
    '--mg-blog-status-success',
    '--mg-blog-space-comfortable',
    '--mg-blog-space-compact',
    '--mg-blog-space-default',
    '--mg-blog-space-hero',
    '--mg-blog-space-micro',
    '--mg-blog-space-panel',
    '--mg-blog-space-section',
    '--mg-blog-space-story',
    '--mg-blog-space-tight',
    '--mg-blog-story-almond',
    '--mg-blog-story-clay',
    '--mg-blog-story-earth',
    '--mg-blog-story-sage',
    '--mg-blog-surface',
    '--mg-blog-surface-muted',
    '--mg-blog-thumbnail-aspect',
    '--mg-blog-topic-card-mobile-max',
    '--mg-blog-topic-card-width',
    '--mg-blog-type-body',
    '--mg-blog-type-body-lg',
    '--mg-blog-type-card',
    '--mg-blog-type-display',
    '--mg-blog-type-heading',
    '--mg-blog-type-hero',
    '--mg-blog-type-inline-mark',
    '--mg-blog-type-inline-note',
    '--mg-blog-type-label',
    '--mg-blog-type-micro',
    '--mg-blog-type-title',
    '--mg-blog-word-slot-height',
    '--mg-blog-word-slot-width',
    '--mg-body-warm',
    '--mg-border-strong',
    '--mg-border-subtle',
    '--mg-button-height-sm',
    '--mg-cashmere-cream',
    '--mg-caution-red',
    '--mg-clay-terracotta',
    '--mg-clay-terracotta-hover',
    '--mg-cocoa-oak',
    '--mg-cream-soft',
    '--mg-current-bg',
    '--mg-current-body',
    '--mg-current-caption',
    '--mg-current-display-hero',
    '--mg-current-display-section',
    '--mg-current-label',
    '--mg-current-surface',
    '--mg-current-text',
    '--mg-current-title',
    '--mg-disabled-surface',
    '--mg-disabled-text',
    '--mg-fg',
    '--mg-focus-ring',
    '--mg-focus-shadow',
    '--mg-focus-shadow-soft',
    '--mg-focus-shadow-inset',
    '--mg-font-brand-ko',
    '--mg-font-latin',
    '--mg-font-size-body-mobile',
    '--mg-font-size-caption-mobile',
    '--mg-font-size-display-hero',
    '--mg-font-size-display-hero-mobile',
    '--mg-font-size-display-section',
    '--mg-font-size-display-section-mobile',
    '--mg-font-size-label-mobile',
    '--mg-font-weight-display',
    '--mg-font-weight-label',
    '--mg-font-weight-regular',
    '--mg-font-weight-strong',
    '--mg-form-field-height',
    '--mg-ink-warm',
    '--mg-kakao-bg',
    '--mg-kakao-text',
    '--mg-letter-spacing',
    '--mg-line-height-body-strong',
    '--mg-line-height-caption',
    '--mg-line-height-display-hero',
    '--mg-line-height-display-section',
    '--mg-line-height-label',
    '--mg-line-height-title',
    '--mg-muted-warm',
    '--mg-navy-soft',
    '--mg-on-dark',
    '--mg-on-terracotta',
    '--mg-overlay-scrim',
    '--mg-overlay-scrim-strong',
    '--mg-paper-white',
    '--mg-radius-md',
    '--mg-radius-sm',
    '--mg-radius-xs',
    '--mg-shadow-elevated',
    '--mg-shadow-hairline',
    '--mg-space-lg',
    '--mg-space-md',
    '--mg-space-section',
    '--mg-space-sm',
    '--mg-space-xl',
    '--mg-space-xs',
    '--mg-space-xxl',
    '--mg-state-danger',
    '--mg-state-danger-hover',
    '--mg-state-danger-border',
    '--mg-state-danger-surface',
    '--mg-state-pending',
    '--mg-state-pending-border',
    '--mg-state-pending-surface',
    '--mg-state-proof',
    '--mg-state-proof-border',
    '--mg-state-proof-surface',
    '--mg-state-success',
    '--mg-state-success-border',
    '--mg-state-success-surface',
    '--mg-success-green',
    '--mg-surface',
    '--mg-surface-card',
    '--mg-surface-card-subtle',
    '--mg-surface-inverse',
    '--mg-surface-page',
    '--mg-surface-page-soft',
    '--mg-surface-raised',
    '--mg-surface-sunken',
    '--mg-surface-translucent',
    '--mg-text-body',
    '--mg-text-muted',
    '--mg-text-primary',
    '--mg-text-soft',
    '--mg-toasted-almond',
    '--mg-verified-navy',
    '--mg-warm-line',
    '--mg-warm-line-strong',
    '--mg-admin-choice-control-size',
    '--mg-admin-editor-backdrop-blur',
    '--mg-admin-gate-marker-size',
    '--mg-admin-progress-track-height',
    '--mg-admin-status-rail-width',
    '--mg-blog-wordmark-label-compact-size',
    '--mg-blog-wordmark-label-size',
    '--mg-blog-wordmark-mobile-brand-size',
    '--mg-blog-wordmark-mobile-label-size',
    '--mg-navigation-backdrop-blur',
    '--mg-overlay-backdrop-blur',
    '--mg-platform-badge-min-height',
    '--mg-showroom-preview-banner-blur',
    '--mg-showroom-preview-content-max-width',
    '--mg-showroom-preview-expired-card-max-width',
    '--mg-showroom-preview-gallery-grid-min',
    '--mg-showroom-preview-hero-grid-min',
    '--mg-showroom-preview-title-size',
    '--mg-visually-hidden-size',
  ],
  rawValueTokenAllowlist: [
    '--mg-admin-preview-chrome-height',
    '--mg-admin-preview-device-width',
    '--mg-admin-preview-handle-height',
    '--mg-admin-preview-handle-width',
    '--mg-admin-preview-ratio-height',
    '--mg-admin-preview-ratio-width',
    '--mg-admin-preview-scroll-max-height',
    '--mg-admin-preview-scroll-offset',
    '--mg-kakao-bg',
    '--mg-kakao-text',
    // Approved reader parity primitives are declared once in blog-experience.css.
    '--mg-blog-reader-caution-surface',
    '--mg-blog-reader-chip-line',
    '--mg-blog-reader-empty-surface',
    '--mg-blog-reader-highlight',
    '--mg-blog-reader-notice',
    '--mg-blog-reader-notice-text',
    '--mg-blog-reader-shadow-ink',
    '--mg-blog-reader-warning-border',
    '--mg-blog-reader-warning-surface',
    '--mg-blog-reader-warning-text',
    '--mg-blog-reader-warm-glass-base',
    // Four scene swatches preserve approved editorial illustration identity.
    '--mg-blog-story-almond',
    '--mg-blog-story-clay',
    '--mg-blog-story-earth',
    '--mg-blog-story-sage',
  ],
  externalDefinitions: [
    '--mg-blog-wordmark-loaded',
    '--admin-bg',
    '--admin-route-block-inset',
    '--admin-border',
    '--admin-surface',
    '--admin-surface-elevated',
    '--admin-text',
    '--admin-text-muted',
    '--admin-text-sub',
    '--color-accent',
    '--color-accent-foreground',
    '--color-accent-hover',
    '--color-bg',
    '--color-border',
    '--color-ring',
    '--color-surface',
    '--color-surface-elevated',
    '--color-text',
    '--color-text-muted',
    '--color-text-sub',
    '--font-regular',
  ],
  sharedLayoutConstants: [
    { name: 'admin-narrow-phone-breakpoint', files: ['src/app/admin/platform/blog/[id]/blog-editor.module.css'], property: '@media', value: '380px', reason: 'Compact blog editor phone layout.' },
    { name: 'admin-preview-phone-breakpoint', files: ['src/app/admin/platform/blog/[id]/preview/preview.module.css', 'src/app/blog/blog.module.css', 'src/app/blog/BlogBrandWordmark.module.css', 'src/components/blog/BlogPostRenderer.module.css'], property: '@media', value: '430px', reason: 'Phone preview and approved blog reader geometry.' },
    { name: 'admin-compact-form-breakpoint', files: ['src/app/admin/platform/[id]/platform-detail.module.css', 'src/components/admin/NodeForm.module.css'], property: '@media', value: '479px', reason: 'Compact admin form layout.' },
    { name: 'admin-dialog-breakpoint', files: ['src/app/admin/platform/blog/[id]/blog-editor.module.css'], property: '@media', value: '520px', reason: 'Blog editor dialog layout.' },
    { name: 'admin-settings-grid-breakpoint', files: ['src/app/admin/platform/settings/settings.module.css'], property: '@media', value: '600px', reason: 'Admin settings grid layout.' },
    { name: 'admin-mobile-breakpoint', files: ['src/app/admin/platform/blog/new/approved-manuscript-intake.module.css', 'src/components/admin/NodeList.module.css', 'src/components/admin/SiteSettingsForm.module.css', 'src/components/platform/ui/PlatformEditorSection.module.css', 'src/components/platform/ui/PlatformPageHeader.module.css', 'src/components/platform/ui/PlatformStatePanel.module.css'], property: '@media', value: '639px', reason: 'Shared admin mobile layout boundary.' },
    { name: 'admin-mobile-alias-breakpoint', files: ['src/app/admin/platform/assets/assets.module.css', 'src/components/platform/ui/PlatformShell.module.css', 'src/styles/munjanggun-brand.css'], property: '@media', value: '640px', reason: 'Legacy admin and platform shell mobile boundary.' },
    { name: 'admin-compact-table-breakpoint', files: ['src/app/admin/platform/assets/assets.module.css', 'src/app/admin/platform/blog/[id]/blog-editor.module.css', 'src/components/blog/BlogConditionChecklist.module.css'], property: '@media', value: '720px', reason: 'Compact table and checklist layout.' },
    { name: 'admin-settings-compact-breakpoint', files: ['src/app/admin/platform/settings/settings.module.css', 'src/app/blog/BlogStoryStage.module.css', 'src/app/blog/BlogTopicRail.module.css'], property: '@media', value: '760px', reason: 'Compact settings and blog story layout.' },
    { name: 'admin-tablet-breakpoint', files: ['src/app/admin/nodes/[id]/page.module.css', 'src/app/admin/platform/assets/assets.module.css', 'src/app/admin/platform/blog/blog-draft-queue.module.css', 'src/app/admin/platform/blog/new/approved-manuscript-intake.module.css', 'src/app/admin/platform/blog/[id]/blog-editor.module.css', 'src/app/admin/platform/platform-admin.module.css', 'src/app/admin/platform/settings/settings.module.css', 'src/app/admin/platform/[id]/platform-detail.module.css', 'src/components/admin/AdminRouteLoading.module.css', 'src/components/admin/HeroConfigurator.module.css', 'src/components/blog/BlogArticleActions.module.css'], property: '@media', value: '768px', reason: 'Shared tablet layout boundary.' },
    { name: 'admin-tablet-table-breakpoint', files: ['src/app/admin/platform/assets/assets.module.css', 'src/app/admin/platform/platform-admin.module.css', 'src/app/blog/BlogStoryStage.module.css'], property: '@media', value: '900px', reason: 'Tablet table and story layout.' },
    { name: 'admin-workspace-max-breakpoint', files: ['src/app/admin/platform/blog/blog-draft-queue.module.css', 'src/app/admin/platform/blog/[id]/blog-editor.module.css'], property: '@media', value: '979px', reason: 'Admin workspace maximum compact boundary.' },
    { name: 'admin-workspace-breakpoint', files: ['src/app/admin/platform/blog/blog-draft-queue.module.css', 'src/app/admin/platform/blog/[id]/blog-editor.module.css', 'src/app/admin/platform/settings/settings.module.css', 'src/components/blog/BlogNavigation.module.css', 'src/components/platform/ui/PlatformPreviewFrame.module.css'], property: '@media', value: '980px', reason: 'Admin workspace and blog navigation boundary.' },
    { name: 'admin-desktop-breakpoint', files: ['src/app/admin/layout.module.css', 'src/components/admin/AdminSidebar.module.css', 'src/components/admin/CollectionForm.module.css', 'src/components/admin/ColorForm.module.css'], property: '@media', value: '1024px', reason: 'Admin desktop shell boundary.' },
    { name: 'admin-wide-max-breakpoint', files: ['src/app/admin/platform/assets/assets.module.css', 'src/app/admin/platform/platform-admin.module.css'], property: '@media', value: '1179px', reason: 'Admin wide layout maximum boundary.' },
    { name: 'admin-wide-breakpoint', files: ['src/app/admin/platform/assets/assets.module.css', 'src/app/admin/platform/blog/blog-draft-queue.module.css', 'src/app/admin/platform/platform-admin.module.css'], property: '@media', value: '1180px', reason: 'Admin wide layout boundary.' },
    { name: 'admin-preview-wide-max-breakpoint', files: ['src/app/admin/platform/blog/[id]/blog-editor.module.css'], property: '@media', value: '1279px', reason: 'Blog editor preview rail boundary.' },
  ],
  layoutConstants: [
    {
      name: 'admin-preview-device-width',
      file: 'src/styles/munjanggun-brand.css',
      property: '--mg-admin-preview-device-width',
      value: '390px',
      reason: 'Named layout value required to preserve the approved UI geometry.',
    },
    {
      name: 'admin-preview-chrome-height',
      file: 'src/styles/munjanggun-brand.css',
      property: '--mg-admin-preview-chrome-height',
      value: '34px',
      reason: 'Named layout value required to preserve the approved UI geometry.',
    },
    {
      name: 'admin-preview-handle-width',
      file: 'src/styles/munjanggun-brand.css',
      property: '--mg-admin-preview-handle-width',
      value: '72px',
      reason: 'Named layout value required to preserve the approved UI geometry.',
    },
    {
      name: 'admin-preview-handle-height',
      file: 'src/styles/munjanggun-brand.css',
      property: '--mg-admin-preview-handle-height',
      value: '5px',
      reason: 'Named layout value required to preserve the approved UI geometry.',
    },
    {
      name: 'admin-preview-scroll-max-height',
      file: 'src/styles/munjanggun-brand.css',
      property: '--mg-admin-preview-scroll-max-height',
      value: '840px',
      reason: 'Named layout value required to preserve the approved UI geometry.',
    },
    {
      name: 'admin-preview-scroll-offset',
      file: 'src/styles/munjanggun-brand.css',
      property: '--mg-admin-preview-scroll-offset',
      value: '244px',
      reason: 'Named layout value required to preserve the approved UI geometry.',
    },
    {
      name: 'legacy-small-control-height',
      file: 'src/styles/munjanggun-brand.css',
      property: '--mg-button-height-sm',
      value: '40px',
      reason: 'Named layout value required to preserve the approved UI geometry.',
    },
    {
      name: 'legacy-mobile-alias-breakpoint',
      file: 'src/styles/munjanggun-brand.css',
      property: '@media',
      value: '640px',
      reason: 'Named layout value required to preserve the approved UI geometry.',
    },
    {
      name: 'approved-blog-tablet-breakpoint',
      files: [
        'src/app/blog/blog.module.css',
        'src/app/blog/BlogConditionComposer.module.css',
        'src/app/blog/BlogFinalExperience.module.css',
        'src/styles/blog-experience.css',
      ],
      property: '@media',
      value: '960px',
      reason: 'Approved blog tablet composition boundary.',
    },
    {
      name: 'approved-blog-mobile-breakpoint',
      files: [
        'src/app/blog/blog.module.css',
        'src/app/blog/BlogConditionComposer.module.css',
        'src/app/blog/BlogFinalExperience.module.css',
        'src/components/blog/BlogArticleActions.module.css',
        'src/components/blog/BlogNavigation.module.css',
        'src/components/customer/PublicUserMenu.module.css',
        'src/styles/blog-experience.css',
      ],
      property: '@media',
      value: '620px',
      reason: 'Approved blog mobile composition boundary.',
    },
    {
      name: 'approved-blog-hero-wide-breakpoint',
      file: 'src/app/blog/BlogHomeHero.module.css',
      property: '@media',
      value: '1100px',
      reason: 'Hero composition switches before the shared tablet boundary.',
    },
    {
      name: 'approved-blog-hero-compact-breakpoint',
      file: 'src/app/blog/BlogHomeHero.module.css',
      property: '@media',
      value: '700px',
      reason: 'Hero lettering and media require an intermediate compact boundary.',
    },
    {
      name: 'approved-blog-hero-phone-breakpoint',
      file: 'src/app/blog/BlogHomeHero.module.css',
      property: '@media',
      value: '390px',
      reason: 'Narrow-phone hero typography boundary.',
    },
    {
      name: 'approved-blog-actions-tablet-max-breakpoint',
      file: 'src/components/blog/BlogArticleActions.module.css',
      property: '@media',
      value: '767px',
      reason: 'Article action rail uses a max-width tablet boundary.',
    },
    {
      name: 'public-user-menu-phone-breakpoint',
      file: 'src/components/customer/PublicUserMenu.module.css',
      property: '@media',
      value: '480px',
      reason: 'Public user menu needs a narrow-phone placement boundary.',
    },
    {
      name: 'admin-intake-feedback-line-height',
      file: 'src/app/admin/platform/blog/new/approved-manuscript-intake.module.css',
      property: 'min-height',
      value: '1.5em',
      reason: 'Feedback reserves one text line relative to its local type size.',
    },
    {
      name: 'admin-page-header-mobile-breakpoint',
      file: 'src/components/platform/ui/PlatformPageHeader.module.css',
      property: '@media',
      value: '639px',
      reason: 'Named layout value required to preserve the approved UI geometry.',
    },
    {
      name: 'admin-editor-section-mobile-breakpoint',
      file: 'src/components/platform/ui/PlatformEditorSection.module.css',
      property: '@media',
      value: '639px',
      reason: 'Named layout value required to preserve the approved UI geometry.',
    },
    {
      name: 'admin-state-panel-mobile-breakpoint',
      file: 'src/components/platform/ui/PlatformStatePanel.module.css',
      property: '@media',
      value: '639px',
      reason: 'Named layout value required to preserve the approved UI geometry.',
    },
    {
      name: 'admin-node-list-mobile-breakpoint',
      file: 'src/components/admin/NodeList.module.css',
      property: '@media',
      value: '639px',
      reason: 'Named layout value required to preserve the approved UI geometry.',
    },
    {
      name: 'admin-site-settings-mobile-breakpoint',
      file: 'src/components/admin/SiteSettingsForm.module.css',
      property: '@media',
      value: '639px',
      reason: 'Named layout value required to preserve the approved UI geometry.',
    },
    {
      name: 'admin-detail-compact-form-breakpoint',
      file: 'src/app/admin/platform/[id]/platform-detail.module.css',
      property: '@media',
      value: '480px',
      reason: 'Named layout value required to preserve the approved UI geometry.',
    },
    {
      name: 'admin-detail-wide-layout-breakpoint',
      file: 'src/app/admin/platform/[id]/platform-detail.module.css',
      property: '@media',
      value: '768px',
      reason: 'Named layout value required to preserve the approved UI geometry.',
    },
    {
      name: 'admin-detail-mobile-layout-breakpoint',
      file: 'src/app/admin/platform/[id]/platform-detail.module.css',
      property: '@media',
      value: '479px',
      reason: 'Named layout value required to preserve the approved UI geometry.',
    },
    {
      name: 'blog-reader-collapse-breakpoint',
      file: 'src/components/blog/BlogPostRenderer.module.css',
      property: '@media',
      value: '820px',
      reason: 'Named layout value required to preserve the approved UI geometry.',
    },
    {
      name: 'blog-reader-mobile-actions-breakpoint',
      file: 'src/components/blog/BlogPostRenderer.module.css',
      property: '@media',
      value: '767px',
      reason: 'Named layout value required to preserve the approved UI geometry.',
    },
    {
      name: 'blog-reader-preview-collapse-container',
      file: 'src/components/blog/BlogPostRenderer.module.css',
      property: '@container',
      value: '820px',
      reason: 'Named layout value required to preserve the approved UI geometry.',
    },
    {
      name: 'blog-reader-preview-phone-container',
      file: 'src/components/blog/BlogPostRenderer.module.css',
      property: '@container',
      value: '430px',
      reason: 'Named layout value required to preserve the approved UI geometry.',
    },
  ],
}

export default uiTokenPolicyConfig
