const uiTokenPolicyConfig = {
  files: [
    'src/styles/generated/brand.css',
    'src/styles/munjanggun-brand.css',
    'src/styles/blog-experience.css',
    'src/components/platform/ui/PlatformButton.module.css',
    'src/components/platform/ui/PlatformIconButton.module.css',
    'src/components/platform/ui/PlatformSegmentedControl.module.css',
    'src/components/platform/ui/PlatformStatusBadge.module.css',
    'src/components/platform/ui/PlatformSwitch.module.css',
    'src/components/platform/ui/PlatformPageHeader.module.css',
    'src/components/platform/ui/PlatformPanel.module.css',
    'src/components/platform/ui/PlatformStatePanel.module.css',
    'src/components/platform/ui/PlatformField.module.css',
    'src/components/platform/ui/PlatformModal.module.css',
    'src/components/platform/ui/PlatformSelect.module.css',
    'src/components/admin/NodeAddModal.module.css',
    'src/components/admin/NodeMoveModal.module.css',
    'src/components/admin/NodeList.module.css',
    'src/components/admin/SiteSettingsForm.module.css',
    'src/app/admin/settings/settings.module.css',
    'src/app/admin/platform/[id]/platform-detail.module.css',
  ],
  generatedFiles: ['src/styles/generated/brand.css'],
  generatedTokenOverrideScopes: [
    {
      file: 'src/styles/munjanggun-brand.css',
      selectors: [
        '[data-mg-theme="portal"]',
        '[data-mg-theme="showroom-dark"]',
        '[data-mg-theme="admin"]',
      ],
    },
  ],
  declarationAllowlist: [
    '--mg-action-primary',
    '--mg-action-primary-active',
    '--mg-action-primary-bg',
    '--mg-action-primary-fg',
    '--mg-action-primary-hover',
    '--mg-action-primary-text',
    '--mg-action-secondary',
    '--mg-action-secondary-hover',
    '--mg-action-secondary-text',
    '--mg-almond-soft',
    '--mg-bg',
    '--mg-blog-accent',
    '--mg-blog-accent-strong',
    '--mg-blog-body',
    '--mg-blog-border',
    '--mg-blog-border-strong',
    '--mg-blog-canvas',
    '--mg-blog-canvas-subtle',
    '--mg-blog-control-size',
    '--mg-blog-cta-surface',
    '--mg-blog-ease-expressive',
    '--mg-blog-font-body',
    '--mg-blog-font-display',
    '--mg-blog-font-wordmark',
    '--mg-blog-glass-border-dark',
    '--mg-blog-glass-border-light',
    '--mg-blog-glass-dark',
    '--mg-blog-glass-hero',
    '--mg-blog-glass-light',
    '--mg-blog-glass-panel',
    '--mg-blog-ink',
    '--mg-blog-inverse',
    '--mg-blog-layout-gutter',
    '--mg-blog-layout-section',
    '--mg-blog-motion-fast',
    '--mg-blog-motion-navigation',
    '--mg-blog-motion-standard',
    '--mg-blog-muted',
    '--mg-blog-radius-card',
    '--mg-blog-radius-compact',
    '--mg-blog-radius-cta',
    '--mg-blog-radius-floating',
    '--mg-blog-radius-footer',
    '--mg-blog-radius-media',
    '--mg-blog-radius-search',
    '--mg-blog-shadow-card',
    '--mg-blog-shadow-floating',
    '--mg-blog-shadow-overlay',
    '--mg-blog-status-danger',
    '--mg-blog-status-success',
    '--mg-blog-surface',
    '--mg-blog-surface-muted',
    '--mg-body-warm',
    '--mg-border-strong',
    '--mg-border-subtle',
    '--mg-button-height-sm',
    '--mg-cashmere-cream',
    '--mg-caution-red',
    '--mg-clay-terracotta',
    '--mg-clay-terracotta-hover',
    '--mg-cocoa-oak',
    '--mg-cream-soft',
    '--mg-current-bg',
    '--mg-current-body',
    '--mg-current-caption',
    '--mg-current-display-hero',
    '--mg-current-display-section',
    '--mg-current-label',
    '--mg-current-surface',
    '--mg-current-text',
    '--mg-disabled-surface',
    '--mg-disabled-text',
    '--mg-fg',
    '--mg-focus-ring',
    '--mg-font-brand-ko',
    '--mg-font-latin',
    '--mg-font-size-body-mobile',
    '--mg-font-size-caption-mobile',
    '--mg-font-size-display-hero',
    '--mg-font-size-display-hero-mobile',
    '--mg-font-size-display-section',
    '--mg-font-size-display-section-mobile',
    '--mg-font-size-label-mobile',
    '--mg-font-weight-display',
    '--mg-font-weight-label',
    '--mg-font-weight-regular',
    '--mg-font-weight-strong',
    '--mg-form-field-height',
    '--mg-ink-warm',
    '--mg-kakao-bg',
    '--mg-kakao-text',
    '--mg-letter-spacing',
    '--mg-line-height-body-strong',
    '--mg-line-height-caption',
    '--mg-line-height-display-hero',
    '--mg-line-height-display-section',
    '--mg-line-height-label',
    '--mg-muted-warm',
    '--mg-navy-soft',
    '--mg-on-dark',
    '--mg-on-terracotta',
    '--mg-overlay-scrim',
    '--mg-paper-white',
    '--mg-radius-md',
    '--mg-radius-sm',
    '--mg-radius-xs',
    '--mg-shadow-elevated',
    '--mg-space-lg',
    '--mg-space-md',
    '--mg-space-section',
    '--mg-space-sm',
    '--mg-space-xl',
    '--mg-space-xs',
    '--mg-space-xxl',
    '--mg-state-danger',
    '--mg-state-danger-hover',
    '--mg-state-danger-surface',
    '--mg-state-pending',
    '--mg-state-pending-surface',
    '--mg-state-proof',
    '--mg-state-success',
    '--mg-state-success-surface',
    '--mg-success-green',
    '--mg-surface',
    '--mg-surface-card',
    '--mg-surface-card-subtle',
    '--mg-surface-inverse',
    '--mg-surface-page',
    '--mg-surface-page-soft',
    '--mg-surface-raised',
    '--mg-surface-sunken',
    '--mg-text-body',
    '--mg-text-muted',
    '--mg-text-primary',
    '--mg-text-soft',
    '--mg-toasted-almond',
    '--mg-verified-navy',
    '--mg-warm-line',
    '--mg-warm-line-strong',
  ],
  rawValueTokenAllowlist: [
    '--mg-kakao-bg',
    '--mg-kakao-text',
  ],
  externalDefinitions: [
    '--admin-bg',
    '--admin-border',
    '--admin-surface',
    '--admin-surface-elevated',
    '--admin-text',
    '--admin-text-muted',
    '--admin-text-sub',
    '--color-accent',
    '--color-accent-foreground',
    '--color-accent-hover',
    '--color-bg',
    '--color-border',
    '--color-ring',
    '--color-surface',
    '--color-surface-elevated',
    '--color-text',
    '--color-text-muted',
    '--color-text-sub',
    '--font-regular',
  ],
  layoutConstants: [
    {
      name: 'legacy-small-control-height',
      file: 'src/styles/munjanggun-brand.css',
      property: '--mg-button-height-sm',
      value: '40px',
    },
    {
      name: 'legacy-mobile-alias-breakpoint',
      file: 'src/styles/munjanggun-brand.css',
      property: '@media',
      value: '640px',
    },
    {
      name: 'approved-blog-search-radius',
      file: 'src/styles/blog-experience.css',
      property: '--mg-blog-radius-search',
      value: '28px',
    },
    {
      name: 'approved-blog-cta-radius',
      file: 'src/styles/blog-experience.css',
      property: '--mg-blog-radius-cta',
      value: '30px',
    },
    {
      name: 'approved-blog-tablet-breakpoint',
      file: 'src/styles/blog-experience.css',
      property: '@media',
      value: '960px',
    },
    {
      name: 'approved-blog-mobile-breakpoint',
      file: 'src/styles/blog-experience.css',
      property: '@media',
      value: '620px',
    },
    {
      name: 'approved-blog-tablet-section-spacing',
      file: 'src/styles/blog-experience.css',
      property: '--mg-blog-layout-section',
      value: '104px',
    },
    {
      name: 'approved-blog-mobile-section-spacing',
      file: 'src/styles/blog-experience.css',
      property: '--mg-blog-layout-section',
      value: '84px',
    },
    {
      name: 'admin-page-header-mobile-breakpoint',
      file: 'src/components/platform/ui/PlatformPageHeader.module.css',
      property: '@media',
      value: '639px',
    },
    {
      name: 'admin-state-panel-mobile-breakpoint',
      file: 'src/components/platform/ui/PlatformStatePanel.module.css',
      property: '@media',
      value: '639px',
    },
    {
      name: 'admin-node-list-mobile-breakpoint',
      file: 'src/components/admin/NodeList.module.css',
      property: '@media',
      value: '639px',
    },
    {
      name: 'admin-site-settings-mobile-breakpoint',
      file: 'src/components/admin/SiteSettingsForm.module.css',
      property: '@media',
      value: '639px',
    },
    {
      name: 'admin-detail-compact-form-breakpoint',
      file: 'src/app/admin/platform/[id]/platform-detail.module.css',
      property: '@media',
      value: '480px',
    },
    {
      name: 'admin-detail-wide-layout-breakpoint',
      file: 'src/app/admin/platform/[id]/platform-detail.module.css',
      property: '@media',
      value: '768px',
    },
    {
      name: 'admin-detail-mobile-layout-breakpoint',
      file: 'src/app/admin/platform/[id]/platform-detail.module.css',
      property: '@media',
      value: '479px',
    },
  ],
}

export default uiTokenPolicyConfig
